const API="https://zbtvhoutdmlszsngihpn.supabase.co/functions/v1/monitor-api-final",AUTH="https://zbtvhoutdmlszsngihpn.supabase.co",PUB="sb_publishable_pgxvM76yy7dQORnBBq5TUQ_fiyz_OQz";
const $=id=>document.getElementById(id);let session=JSON.parse(sessionStorage.getItem("monitor-session")||"null"),monitors=[],channels=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function msg(s){$("loginMsg").textContent=s}function toast(s){$("toast").textContent=s;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2500)}
async function login(e){e.preventDefault();msg("Signing in…");try{const r=await fetch(API+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("loginEmail").value,password:$("loginPassword").value})}),d=await r.json();if(!r.ok)throw Error(d.error||"Sign-in failed");session=d.session;sessionStorage.setItem("monitor-session",JSON.stringify(session));await boot()}catch(e){msg(e.message)}}
async function refreshSession(){if(!session?.refresh_token)return false;const r=await fetch(AUTH+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{"apikey":PUB,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok)return false;session=await r.json();sessionStorage.setItem("monitor-session",JSON.stringify(session));return true}
async function api(path,opts={},retry=true){const h=Object.assign({"Content-Type":"application/json","Authorization":"Bearer "+session.access_token},opts.headers||{});let r=await fetch(API+"/"+path,Object.assign({},opts,{headers:h}));if(r.status===401&&retry&&await refreshSession())return api(path,opts,false);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function fillMonitor(m){$("monitorId").value=m.id;$("mName").value=m.name;$("mUrl").value=m.url;$("mInterval").value=m.interval_seconds;$("mTimeout").value=m.timeout_ms;$("mFailure").value=m.failure_threshold;$("mRecovery").value=m.recovery_threshold;$("mMin").value=m.expected_status_min;$("mMax").value=m.expected_status_max;$("mEnabled").checked=m.enabled;window.scrollTo({top:0,behavior:"smooth"})}
async function loadMonitors(){const d=await api("operator/monitors");monitors=d.monitors||[];$("monitorList").innerHTML=monitors.map(m=>'<div class="op-row"><div><strong>'+esc(m.name)+'</strong><small>'+esc(m.url)+' · '+esc(m.interval_seconds)+'s · '+esc(m.last_status||"unknown")+'</small></div><div class="op-row-actions"><button class="ghost-btn edit-monitor" data-id="'+m.id+'">Edit</button><button class="ghost-btn delete-monitor danger" data-id="'+m.id+'">Delete</button></div></div>').join("")||'<div class="form-note">No monitors configured.</div>';const opts='<option value="">None</option>'+monitors.map(m=>'<option value="'+m.id+'">'+esc(m.name)+'</option>').join("");$("maintenanceMonitor").innerHTML=opts.replace('<option value="">None</option>','');$("ruleMonitor").innerHTML='<option value="">All monitors</option>'+monitors.map(m=>'<option value="'+m.id+'">'+esc(m.name)+'</option>').join("");$("depMonitor").innerHTML=opts}
async function loadIncidents(){const d=await api("operator/incidents");$("incidentList").innerHTML=(d.incidents||[]).slice(0,50).map(i=>'<div class="op-row"><div><strong>'+esc(i.reason)+'</strong><small>'+esc(i.status)+' · '+new Date(i.started_at).toLocaleString()+(i.duration_seconds!=null?' · '+Math.round(i.duration_seconds/60)+' min':'')+'</small></div><div class="op-row-actions">'+(i.status!=="resolved"?'<button class="ghost-btn resolve-incident" data-id="'+i.id+'">Resolve</button>':'')+'</div></div>').join("")||'<div class="form-note">No incidents.</div>'}
async function loadMaintenance(){const d=await api("operator/maintenance");$("maintenanceList").innerHTML=(d.maintenance||[]).map(m=>'<div class="op-row"><div><strong>'+esc(m.reason)+'</strong><small>'+new Date(m.starts_at).toLocaleString()+' → '+new Date(m.ends_at).toLocaleString()+'</small></div><button class="ghost-btn delete-maint" data-id="'+m.id+'">Delete</button></div>').join("")||'<div class="form-note">No maintenance windows.</div>'}
async function loadAlerts(){const [c,r]=await Promise.all([api("operator/alert-channels"),api("operator/alert-rules")]);channels=c.channels||[];$("channelList").innerHTML=channels.map(x=>'<div class="op-row"><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.channel_type)+' · '+esc(x.destination)+'</small></div><button class="ghost-btn delete-channel" data-id="'+x.id+'">Delete</button></div>').join("")||'<div class="form-note">No alert channels.</div>';$("ruleChannel").innerHTML=channels.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join("");$("ruleList").innerHTML=(r.rules||[]).map(x=>'<div class="op-row"><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.trigger_type)+' · '+x.consecutive_failures+' failures</small></div><button class="ghost-btn delete-rule" data-id="'+x.id+'">Delete</button></div>').join("")||'<div class="form-note">No alert rules.</div>'}
async function loadDeployments(){const d=await api("operator/deployments");$("deploymentList").innerHTML=(d.deployments||[]).slice(0,30).map(x=>'<div class="op-row"><div><strong>'+esc(x.provider)+' · '+esc(x.status)+'</strong><small>'+esc((x.sha||"").slice(0,8))+' · '+new Date(x.created_at).toLocaleString()+'</small></div></div>').join("")||'<div class="form-note">No deployments.</div>'}
async function boot(){try{const me=await api("operator/me");$("operatorIdentity").textContent="Signed in as "+me.email;$("loginView").classList.add("hidden");$("console").classList.remove("hidden");await Promise.all([loadMonitors(),loadIncidents(),loadMaintenance(),loadAlerts(),loadDeployments()])}catch(e){session=null;sessionStorage.removeItem("monitor-session");$("loginView").classList.remove("hidden");$("console").classList.add("hidden");msg(e.message)}}
$("loginForm").addEventListener("submit",login);
$("logout").addEventListener("click",()=>{session=null;sessionStorage.removeItem("monitor-session");location.reload()});
$("monitorForm").addEventListener("submit",async e=>{e.preventDefault();try{const b={name:$("mName").value,url:$("mUrl").value,interval_seconds:Number($("mInterval").value),timeout_ms:Number($("mTimeout").value),failure_threshold:Number($("mFailure").value),recovery_threshold:Number($("mRecovery").value),expected_status_min:Number($("mMin").value),expected_status_max:Number($("mMax").value),enabled:$("mEnabled").checked,tags:["production"]},id=$("monitorId").value;await api(id?"operator/monitors/"+id:"operator/monitors",{method:id?"PATCH":"POST",body:JSON.stringify(b)});$("monitorForm").reset();$("mInterval").value=60;$("mTimeout").value=8000;$("mFailure").value=2;$("mRecovery").value=1;$("mMin").value=200;$("mMax").value=399;$("mEnabled").checked=true;$("monitorId").value="";await loadMonitors();toast("Monitor saved")}catch(e){toast(e.message)}});
$("resetMonitor").addEventListener("click",()=>{$("monitorForm").reset();$("monitorId").value=""});
$("monitorList").addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;try{if(b.classList.contains("edit-monitor"))fillMonitor(monitors.find(m=>m.id===b.dataset.id));else{await api("operator/monitors/"+b.dataset.id,{method:"DELETE"});await loadMonitors();toast("Monitor deleted")}}catch(x){toast(x.message)}});
$("incidentList").addEventListener("click",async e=>{const b=e.target.closest(".resolve-incident");if(!b)return;try{await api("operator/incidents/"+b.dataset.id,{method:"PATCH",body:JSON.stringify({status:"resolved"})});await loadIncidents();toast("Incident resolved")}catch(x){toast(x.message)}});
$("maintenanceForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("operator/maintenance",{method:"POST",body:JSON.stringify({monitor_id:$("maintenanceMonitor").value,starts_at:new Date($("maintenanceStart").value).toISOString(),ends_at:new Date($("maintenanceEnd").value).toISOString(),reason:$("maintenanceReason").value})});await loadMaintenance();e.target.reset();toast("Maintenance scheduled")}catch(x){toast(x.message)}});
$("maintenanceList").addEventListener("click",async e=>{const b=e.target.closest(".delete-maint");if(!b)return;try{await api("operator/maintenance/"+b.dataset.id,{method:"DELETE"});loadMaintenance()}catch(x){toast(x.message)}});
$("channelForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("operator/alert-channels",{method:"POST",body:JSON.stringify({name:$("channelName").value,channel_type:$("channelType").value,destination:$("channelDestination").value})});e.target.reset();await loadAlerts();toast("Alert channel added")}catch(x){toast(x.message)}});
$("channelList").addEventListener("click",async e=>{const b=e.target.closest(".delete-channel");if(!b)return;try{await api("operator/alert-channels/"+b.dataset.id,{method:"DELETE"});loadAlerts()}catch(x){toast(x.message)}});
$("ruleForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("operator/alert-rules",{method:"POST",body:JSON.stringify({name:$("ruleName").value,channel_id:$("ruleChannel").value,monitor_id:$("ruleMonitor").value||null,trigger_type:$("ruleTrigger").value,consecutive_failures:Number($("ruleFailures").value)})});e.target.reset();$("ruleFailures").value=2;await loadAlerts();toast("Alert rule added")}catch(x){toast(x.message)}});
$("ruleList").addEventListener("click",async e=>{const b=e.target.closest(".delete-rule");if(!b)return;try{await api("operator/alert-rules/"+b.dataset.id,{method:"DELETE"});loadAlerts()}catch(x){toast(x.message)}});
$("deploymentForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("operator/deployments",{method:"POST",body:JSON.stringify({provider:$("depProvider").value,status:$("depStatus").value,sha:$("depSha").value,branch:$("depBranch").value,url:$("depUrl").value||null,monitor_id:$("depMonitor").value||null})});e.target.reset();$("depProvider").value="manual";$("depBranch").value="main";await loadDeployments();toast("Deployment recorded")}catch(x){toast(x.message)}});
if(session)boot();