create extension if not exists pg_cron;
create extension if not exists pg_net;

create schema if not exists monitoring;

create table if not exists monitoring.monitors (id uuid primary key default gen_random_uuid(), name text not null, url text not null unique, method text not null default 'GET', interval_seconds integer not null default 60, timeout_ms integer not null default 8000, failure_threshold integer not null default 2, recovery_threshold integer not null default 1, expected_status_min integer not null default 200, expected_status_max integer not null default 399, enabled boolean not null default true, maintenance boolean not null default false, tags jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), last_checked_at timestamptz, last_status text, last_http_status integer, last_latency_ms integer);
create table if not exists monitoring.check_results (id bigint generated always as identity primary key, monitor_id uuid not null references monitoring.monitors(id) on delete cascade, checked_at timestamptz not null default now(), status text not null, http_status integer, latency_ms integer, error_code text, error_message text, response_size_bytes integer, region text, created_at timestamptz not null default now());
create index if not exists check_results_monitor_checked_idx on monitoring.check_results(monitor_id,checked_at desc);
create table if not exists monitoring.incidents (id uuid primary key default gen_random_uuid(), monitor_id uuid not null references monitoring.monitors(id) on delete cascade, status text not null default 'open', reason text not null, first_failure_at timestamptz not null, started_at timestamptz not null default now(), investigating_at timestamptz, resolved_at timestamptz, recovery_at timestamptz, failure_count integer not null default 1, recovery_count integer not null default 0, duration_seconds bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists incidents_one_active_per_monitor_idx on monitoring.incidents(monitor_id) where status <> 'resolved';
create table if not exists monitoring.maintenance_windows (id uuid primary key default gen_random_uuid(), monitor_id uuid not null references monitoring.monitors(id) on delete cascade, starts_at timestamptz not null, ends_at timestamptz not null, reason text not null default 'Scheduled maintenance', created_at timestamptz not null default now(), check(ends_at>starts_at));
create table if not exists monitoring.deployments (id uuid primary key default gen_random_uuid(), monitor_id uuid references monitoring.monitors(id) on delete set null, provider text not null, external_id text, status text not null, sha text, branch text, started_at timestamptz, finished_at timestamptz, url text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(provider,external_id));
create table if not exists monitoring.alert_channels (id uuid primary key default gen_random_uuid(), name text not null, channel_type text not null, destination text not null, enabled boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists monitoring.alert_rules (id uuid primary key default gen_random_uuid(), name text not null, monitor_id uuid references monitoring.monitors(id) on delete cascade, channel_id uuid not null references monitoring.alert_channels(id) on delete cascade, trigger_type text not null, consecutive_failures integer not null default 2, enabled boolean not null default true, created_at timestamptz not null default now());
create table if not exists monitoring.alert_deliveries (id bigint generated always as identity primary key, rule_id uuid references monitoring.alert_rules(id) on delete set null, incident_id uuid references monitoring.incidents(id) on delete set null, channel_type text not null, destination text not null, event_type text not null, status text not null, response_code integer, error_message text, created_at timestamptz not null default now());
create table if not exists monitoring.operator_access (email text primary key, enabled boolean not null default true, created_at timestamptz not null default now());
create table if not exists monitoring.rate_limits (bucket_key text primary key, window_started_at timestamptz not null default now(), hits integer not null default 0);
alter table monitoring.monitors enable row level security; alter table monitoring.check_results enable row level security; alter table monitoring.incidents enable row level security; alter table monitoring.maintenance_windows enable row level security; alter table monitoring.deployments enable row level security; alter table monitoring.alert_channels enable row level security; alter table monitoring.alert_rules enable row level security; alter table monitoring.alert_deliveries enable row level security; alter table monitoring.operator_access enable row level security; alter table monitoring.rate_limits enable row level security;
create or replace function monitoring.consume_rate_limit(p_bucket text,p_limit integer,p_window_seconds integer) returns boolean language plpgsql security definer set search_path=monitoring,public as $$ begin insert into monitoring.rate_limits(bucket_key,window_started_at,hits) values(p_bucket,now(),1) on conflict(bucket_key) do update set window_started_at=case when extract(epoch from(now()-monitoring.rate_limits.window_started_at))>=p_window_seconds then now() else monitoring.rate_limits.window_started_at end,hits=case when extract(epoch from(now()-monitoring.rate_limits.window_started_at))>=p_window_seconds then 1 else monitoring.rate_limits.hits+1 end; return (select hits<=p_limit from monitoring.rate_limits where bucket_key=p_bucket); end; $$;
create or replace function monitoring.cleanup_old_data() returns void language plpgsql security definer set search_path=monitoring,public as $$ begin delete from monitoring.check_results where checked_at<now()-interval '90 days'; delete from monitoring.alert_deliveries where created_at<now()-interval '180 days'; delete from monitoring.deployments where created_at<now()-interval '365 days'; delete from monitoring.rate_limits where window_started_at<now()-interval '1 hour'; end; $$;